spring:
  application:
    name: message-server
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MICROM}?createDatabaseIfNotExist=true
      &allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
      &characterEncoding=UTF-8
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
